simulation:
  time_steps: 1000
  dt: 0.1
  num_vehicles: 1
  waypoint_radius: 2.0
agents:
    name: "albert"
    id: 1
    waypoints:
      1: [-300.0, -200.0, 0.0]
      2: [200.0, -100.0, 1.0]
      3: [0.0, 200.0, 0.5]
vehicles:
  id: 1
  ics: [0.0, 0.0, 0.0]
