simulation:
  sim_name: "TEST"
  time_steps: 1000
  dt: 0.1
  num_vehicles: 1
  waypoint_radius: 2.0
  vehicle_type: "simple"
  
  spawn_explicit: true        # spawn all agents at specific state
  spawn_distributed: false      # for large N, spread agents out evenly
  performance: 1               # waypoint[0], rendevous[1], swarm control[2]

  neighbor_radius: 80.0

  log_events: false

agent_manager:
  connection_radius: 100.0
  desired_separation: 50.0
  leader_id: 7
  
agents:
    # LEADERS
  - name: "leader"
    id: 7
    waypoint_mode: true
    ics: [0.0, 0.0, 0.0]
    connection_radius: 150.0
    role: "leader"
    desired_separation: 50.0
    waypoints: 
      - [100.0, 0.0]
      - [100.0, 100.0]
      - [0.0, 100.0]
      - [100.0, 200.0]
    loop_waypoints: true
    # FOLLOWERS
  # - name: "albert2"
  #   id: 2
  #   waypoint_mode: true
  #   ics: [20.0, 20.0, 20.0]
  #   connection_radius: 150.0
  #   role: "follower"
  #   desired_separation: 15.0

  # - name: "albert3" 
  #   id: 3
  #   waypoint_mode: true
  #   ics: [0.0, 20.0, 0.0]
  #   connection_radius: 150.0
  #   role: "follower"
  #   desired_separation: 15.0

  # - name: "albert4"
  #   id: 4
  #   waypoint_mode: true
  #   ics: [21.0, 0.0, 20.0]
  #   connection_radius: 150.0
  #   role: "follower"
  #   desired_separation: 15.0
