simulation:
  sim_name: "TEST"
  time_steps: 1000
  dt: 0.1
  num_vehicles: 1
  waypoint_radius: 2.0
  
  spawn_explicit: true        # spawn all agents at specific state
  spawn_distributed: false      # for large N, spread agents out evenly
  performance: 1               # waypoint[0], rendevous[1], swarm control[2]

  neighbor_radius: 80.0

  log_events: false
  
vehicles:
  - id: 1
    ics: [0.0, 0.0, 0.0]
    agent: "albert"

  - id: 2
    ics: [20.0, 20.0, 0.0]
    agent: "albert"
  
  - id: 3
    ics: [20.0, 0.0, 0.0]
    agent: "albert"

  - id: 4
    ics: [0.0, 20.0, 0.0]
    agent: "albert"

agents:
  - name: "albert1"
    id: 1
    waypoint_mode: true
    leader: true
    ics: [0.0, 0.0, 0.0]
    connection_radius: 50.0
    role: "leader"

  - name: "albert2"
    id: 2
    waypoint_mode: true
    leader: true 
    ics: [20.0, 20.0, 20.0]
    connection_radius: 50.0
    role: "follower"

  - name: "albert3" 
    id: 3
    waypoint_mode: true
    leader: true 
    ics: [2000.0, 2000.0, 20.0]
    connection_radius: 50.0
    role: "follower"

  - name: "albert4"
    id: 4
    waypoint_mode: true
    leader: true 
    ics: [21.0, 0.0, 20.0]
    connection_radius: 50.0
    role: "follower"
